name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Every day; adjust as needed
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add upstream remote
        run: git remote add upstream https://github.com/zed-industries/zed.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main into main branch
        run: |
          git checkout main
          git merge upstream/main --no-edit || echo "Nothing to merge"

      - name: Push changes to your fork
        run: git push origin main
