name: Windows Build & Release

on:
  push:
    branches: [main]
    tags:
      - '*'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Add Rust components
        run: rustup component add clippy rustfmt

      - name: Install dependencies via Chocolatey
        run: |
          choco install -y visualstudio2022buildtools visualstudio2022-workload-vctools cmake vulkan-sdk windows-sdk-10-version-2104

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Enable Long Paths Support
        run: |
          git config --system core.longpaths true
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - name: Build Zed release
        run: cargo build --workspace --release

      - name: Upload built binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows-release
          path: target/release/zed.exe

      - name: Create GitHub Release on tag push
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: target/release/zed.exe
          token: ${{ secrets.GITHUB_TOKEN }}
