name: Build Zed Release on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Set up MSVC build tools using Chocolatey
        shell: powershell
        run: |
          choco install visualstudio2022buildtools --yes --force --no-progress --package-parameters `
            "--add Microsoft.VisualStudio.Workload.VCTools `
            --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
            --add Microsoft.VisualStudio.Component.VC.CMake.Project `
            --add Microsoft.VisualStudio.Component.Windows11SDK.26100 `
            --add Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre `
            --includeRecommended --includeOptional"

      - name: Install CMake
        shell: powershell
        run: choco install cmake --yes --force --no-progress --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: Add Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build (Release)
        run: cargo build --release

      - name: Upload Release Executable
        uses: actions/upload-artifact@v4
        with:
          name: zed-release-executable
          path: target/release/zed*.exe
